//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbBankingEntities : DbContext
    {
        public dbBankingEntities()
            : base("name=dbBankingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAccounts> tblAccounts { get; set; }
        public virtual DbSet<tblBeneficiary> tblBeneficiary { get; set; }
        public virtual DbSet<tblBlocked> tblBlocked { get; set; }
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
        public virtual DbSet<tblInternetBanking> tblInternetBanking { get; set; }
        public virtual DbSet<tblLogin> tblLogin { get; set; }
        public virtual DbSet<tblStatus> tblStatus { get; set; }
        public virtual DbSet<tblTransaction> tblTransaction { get; set; }
    
        public virtual ObjectResult<proc_getAllApprovedAppStatus_Result> proc_getAllApprovedAppStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getAllApprovedAppStatus_Result>("proc_getAllApprovedAppStatus");
        }
    
        public virtual ObjectResult<proc_getAllAppStatus_Result> proc_getAllAppStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getAllAppStatus_Result>("proc_getAllAppStatus");
        }
    
        public virtual ObjectResult<proc_getAllCustDetails_Result> proc_getAllCustDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getAllCustDetails_Result>("proc_getAllCustDetails");
        }
    
        public virtual ObjectResult<proc_getAllDeniedAppStatus_Result> proc_getAllDeniedAppStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getAllDeniedAppStatus_Result>("proc_getAllDeniedAppStatus");
        }
    
        public virtual ObjectResult<proc_getAllPendingAppStatus_Result> proc_getAllPendingAppStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getAllPendingAppStatus_Result>("proc_getAllPendingAppStatus");
        }
    
        public virtual ObjectResult<proc_getAppStatus_Result> proc_getAppStatus(string cust_id)
        {
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getAppStatus_Result>("proc_getAppStatus", cust_idParameter);
        }
    
        public virtual ObjectResult<proc_GetBlocked_Result> proc_GetBlocked(string cust_id, string acc_number)
        {
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            var acc_numberParameter = acc_number != null ?
                new ObjectParameter("acc_number", acc_number) :
                new ObjectParameter("acc_number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetBlocked_Result>("proc_GetBlocked", cust_idParameter, acc_numberParameter);
        }
    
        public virtual ObjectResult<proc_getCustDetails_Result> proc_getCustDetails(string cust_id)
        {
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getCustDetails_Result>("proc_getCustDetails", cust_idParameter);
        }
    
        public virtual int proc_InsBlocked(string cust_id)
        {
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_InsBlocked", cust_idParameter);
        }
    
        public virtual int proc_setUserLogin(string cust_id, string acc_number, string user_type, string pwd)
        {
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            var acc_numberParameter = acc_number != null ?
                new ObjectParameter("acc_number", acc_number) :
                new ObjectParameter("acc_number", typeof(string));
    
            var user_typeParameter = user_type != null ?
                new ObjectParameter("user_type", user_type) :
                new ObjectParameter("user_type", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_setUserLogin", cust_idParameter, acc_numberParameter, user_typeParameter, pwdParameter);
        }
    
        public virtual int proc_toggleAppStatus(Nullable<int> ref_no)
        {
            var ref_noParameter = ref_no.HasValue ?
                new ObjectParameter("ref_no", ref_no) :
                new ObjectParameter("ref_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_toggleAppStatus", ref_noParameter);
        }
    
        public virtual ObjectResult<proc_UserLogin_Result> proc_UserLogin(string cust_id, string pwd)
        {
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("pwd", pwd) :
                new ObjectParameter("pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserLogin_Result>("proc_UserLogin", cust_idParameter, pwdParameter);
        }
    
        public virtual int proc_UserReg(string aadhar, string cust_id, string title, string first_name, string middle_name, string last_name, string father_name, string phone, string cust_mail, Nullable<System.DateTime> dob, Nullable<int> age, string res_address, string perm_address, string gender)
        {
            var aadharParameter = aadhar != null ?
                new ObjectParameter("aadhar", aadhar) :
                new ObjectParameter("aadhar", typeof(string));
    
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var middle_nameParameter = middle_name != null ?
                new ObjectParameter("middle_name", middle_name) :
                new ObjectParameter("middle_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var cust_mailParameter = cust_mail != null ?
                new ObjectParameter("cust_mail", cust_mail) :
                new ObjectParameter("cust_mail", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            var res_addressParameter = res_address != null ?
                new ObjectParameter("res_address", res_address) :
                new ObjectParameter("res_address", typeof(string));
    
            var perm_addressParameter = perm_address != null ?
                new ObjectParameter("perm_address", perm_address) :
                new ObjectParameter("perm_address", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UserReg", aadharParameter, cust_idParameter, titleParameter, first_nameParameter, middle_nameParameter, last_nameParameter, father_nameParameter, phoneParameter, cust_mailParameter, dobParameter, ageParameter, res_addressParameter, perm_addressParameter, genderParameter);
        }
    
        public virtual int proc_denyAppStatus(Nullable<int> ref_no)
        {
            var ref_noParameter = ref_no.HasValue ?
                new ObjectParameter("ref_no", ref_no) :
                new ObjectParameter("ref_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_denyAppStatus", ref_noParameter);
        }
    
        public virtual ObjectResult<proc_getAllCustDetailsAlongWithAppStatus_Result> proc_getAllCustDetailsAlongWithAppStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getAllCustDetailsAlongWithAppStatus_Result>("proc_getAllCustDetailsAlongWithAppStatus");
        }
    
        public virtual ObjectResult<proc_getApplicationByRefno_Result> proc_getApplicationByRefno(Nullable<int> ref_no)
        {
            var ref_noParameter = ref_no.HasValue ?
                new ObjectParameter("ref_no", ref_no) :
                new ObjectParameter("ref_no", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_getApplicationByRefno_Result>("proc_getApplicationByRefno", ref_noParameter);
        }
    
        public virtual ObjectResult<proc_verifyMail_Result> proc_verifyMail(string cust_id)
        {
            var cust_idParameter = cust_id != null ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_verifyMail_Result>("proc_verifyMail", cust_idParameter);
        }
    }
}
