//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatu
    {
        public string ref_no { get; set; }
        public string aadhar { get; set; }
        public string app_by { get; set; }
        public string acc_status { get; set; }
        public System.DateTime app_date { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
